module.exports = {
    pro: [{
        "id": 27,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "九悦庭雅宅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "江西九江",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "150㎡",
        "txtPlace": 7,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "880",
            "top": "0"
        }, {
            "url": "c4.jpg",
            "size": "860x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "880",
            "top": "460"
        }, {
            "url": "c6.jpg",
            "size": "860x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c7.jpg",
            "size": "420x210",
            "left": "880",
            "top": "690"
        }],
        "designConcept": "",
        "content": "<div><p>完成时间：2017年1月</p><p>主要材料：乳胶漆、大理石、藤编壁纸、木饰面</p><p>在家居设计中简约风越来越受到人们的青睐，成为设计界的流行元素，它以少胜多的设计理念，玩转出一个温馨、优雅的家居环境。</p><p>当初这对90后夫妇找到设计师，希望能为他们设计婚房。看着他们一脸欣喜，本着只羡鸳鸯不羡仙的心情，设计师也提出自己的想法同他们一起沟通交流，业主很信任，所以整个工程都很顺利的开展。</p><p>家居设计不仅是停留在家居选择、空间布局、材质、颜色的组合选择等形式上，设计师通过这些外在的设计形式赋予内在的“灵魂内核”，而且也希望业主在今后的生活过程中细细品味日子。</p><p>执着于空间的比例规划设计师巧妙的构思把各个空间流畅的连接起来，让更多的自然光照进室内，而开拓的空间使业主在今后的生活相处中更加轻松愉悦，交流更加便捷。两处空间的艺术挂画和抱枕相映成趣、相互呼应，从而打造强烈的空间感。</p><p>空间整体以高冷灰为主色调来打造极简现代的都市风格，细腻色彩的点缀为空间营造出时尚小资情调。</p></div>",
        "dtlImgType": "",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg"]
    }, {
        "id": 28,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "庐山私人住宅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "江西九江",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "300㎡",
        "txtPlace": 4,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "860x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x210",
            "left": "880",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c4.jpg",
            "size": "860x440",
            "left": "440",
            "top": "460"
        }],
        "designConcept": "在设计中以文化为内核，糅合东西方文化，进行提炼和度越，博百家之长， 将西方住宅文化与本地居住理念融合于装饰设计的设计理念，打上地域与人 文内涵的烙印。",
        "content": "",
        "dtlImgType": "",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
    }, {
        "id": 29,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "海南别墅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "海南",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "2000㎡",
        "txtPlace": 4,
        "textRlign": "right",
        "showType": "type_c",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "880",
            "top": "0"
        }, {
            "url": "c4.jpg",
            "size": "860x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "880",
            "top": "460"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "",
        "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
    }, {
        "id": 30,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "江西映日荷花18",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "江西九江",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "380㎡",
        "txtPlace": 5,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "880",
            "top": "0"
        }, {
            "url": "c4.jpg",
            "size": "860x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "880",
            "top": "460"
        }, {
            "url": "c6.jpg",
            "size": "420x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c7.jpg",
            "size": "860x210",
            "left": "440",
            "top": "690"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "",
        "dtlImgs": ["1.png", "3.png", "4.png", "5.png", "6.png"]
    }, {
        "id": 31,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "江西映日荷花99",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "江西九江",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "2200㎡",
        "txtPlace": 5,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x210",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x210",
            "left": "880",
            "top": "0"
        }, {
            "url": "c4.jpg",
            "size": "420x440",
            "left": "0",
            "top": "230"
        }, {
            "url": "c5.jpg",
            "size": "420x440",
            "left": "440",
            "top": "460"
        }, {
            "url": "c6.jpg",
            "size": "420x210",
            "left": "880",
            "top": "230"
        }, {
            "url": "c7.jpg",
            "size": "420x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c8.jpg",
            "size": "420x210",
            "left": "880",
            "top": "690"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "",
        "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
    }, {
        "id": 32,
        "ctg": 5,
        "delete": true, //删除不显示
        "ctgName": "私宅样板房别墅",
        "title": "浙江余姚私宅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "浙江余姚",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "150㎡",
        "txtPlace": 1,
        "textRlign": "right",
        "showType": "single",
        "cover": "c1.jpg",
        "designConcept": "",
        "content": "",
        "dtlImgType": "full",
        "dtlImgs": ["1.png", "2.png"]
    }, {
        "id": 45,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "江西映日荷花",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "江西九江",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "1000㎡",
        "txtPlace": 3,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "880",
            "top": "0"
        }, {
            "url": "c4.jpg",
            "size": "860x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "880",
            "top": "460"
        }, {
            "url": "c6.jpg",
            "size": "860x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c7.jpg",
            "size": "420x210",
            "left": "880",
            "top": "690"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"]
    }, {
        "id": 46,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "合肥旭辉样板间",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "安徽合肥",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "200㎡",
        "txtPlace": 6,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "860x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x210",
            "left": "880",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x210",
            "left": "880",
            "top": "230"
        }, {
            "url": "c4.jpg",
            "size": "420x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c6.jpg",
            "size": "860x440",
            "left": "440",
            "top": "460"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "full",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg"]
    }, {
        "id": 47,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "合肥中海滨湖公馆",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "安徽合肥",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "180㎡",
        "txtPlace": 2,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "860x210",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "880",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "860x210",
            "left": "0",
            "top": "230"
        }, {
            "url": "c4.jpg",
            "size": "420x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c6.jpg",
            "size": "860x210",
            "left": "440",
            "top": "460"
        }, {
            "url": "c7.jpg",
            "size": "860x210",
            "left": "440",
            "top": "690"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "full",
        "dtlImgs": ["1.jpg", "2.jpg"]
    }, {
        "id": 48,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "南通上林苑别墅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "江苏南通",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "600㎡",
        "txtPlace": 1,
        "textRlign": "right",
        "showType": "single",
        "cover": "c1.jpg",
        "designConcept": "",
        "content": "",
        "dtlImgType": "",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", ]
    }, {
        "id": 49,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "汕头中海地产寰宇天下",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "广东汕头",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "500㎡",
        "txtPlace": 7,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "860x210",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "440",
            "top": "230"
        }, {
            "url": "c4.jpg",
            "size": "420x210",
            "left": "880",
            "top": "230"
        }, {
            "url": "c5.jpg",
            "size": "420x210",
            "left": "0",
            "top": "460"
        }, {
            "url": "c6.jpg",
            "size": "860x210",
            "left": "0",
            "top": "690"
        }, {
            "url": "c7.jpg",
            "size": "420x440",
            "left": "880",
            "top": "460"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "full",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
    }, {
        "id": 50,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "上海虹桥239别墅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "中国上海",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "300㎡",
        "txtPlace": 6,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "420x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "880",
            "top": "0"
        }, {
            "url": "c4.jpg",
            "size": "420x440",
            "left": "0",
            "top": "460"
        }, {
            "url": "c5.jpg",
            "size": "420x440",
            "left": "440",
            "top": "460"
        }, {
            "url": "c6.jpg",
            "size": "420x440",
            "left": "880",
            "top": "460"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "full",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
    }, {
        "id": 51,
        "ctg": 5,
        "ctgName": "私宅样板房别墅",
        "title": "上海紫御世家别墅",
        "design": "李宏升",
        "designCom": "御舍设计",
        "location": "中国上海",
        "construction": "御舍（上海）建设工程有限公司",
        "area": "500㎡",
        "txtPlace": 4,
        "textRlign": "right",
        "showType": "type_a",
        "cover": [{
            "url": "c1.jpg",
            "size": "420x440",
            "left": "0",
            "top": "0"
        }, {
            "url": "c2.jpg",
            "size": "860x440",
            "left": "440",
            "top": "0"
        }, {
            "url": "c3.jpg",
            "size": "420x440",
            "left": "0",
            "top": "460"
        }, {
            "url": "c4.jpg",
            "size": "860x440",
            "left": "440",
            "top": "460"
        }],
        "designConcept": "",
        "content": "",
        "dtlImgType": "full",
        "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg"]
    }]
};