module.exports = {
  pro: [
    {
      id: 52,
      ctg: 7,
      ctgName: "户外景观",
      title: "银都名墅",
      design: "梁坤",
      designCom: "御舍设计",
      location: "中国上海",
      construction: "御舍（上海）建设工程有限公司",
      area: "106㎡",
      txtPlace: 4,
      textRlign: "right",
      showType: "type_a", //single type_a type_b
      cover: [
        {
          url: "c1.jpg",
          size: "860x440",
          left: "0",
          top: "0",
        },
        {
          url: "c2.jpg",
          size: "420x440",
          left: "880",
          top: "0",
        },
        {
          url: "c3.jpg",
          size: "420x440",
          left: "0",
          top: "460",
        },
        {
          url: "c4.jpg",
          size: "860x440",
          left: "440",
          top: "460",
        },
      ],
      designConcept: "",
      content: "",
      dtlImgType: "", //full
      dtlImgs: ["1.jpg", "2.jpg", "4.jpg", "6.jpg", "7.jpg"],
    },
    {
      id: 53,
      ctg: 7,
      ctgName: "户外景观",
      title: "水都南岸",
      design: "李向阳",
      designCom: "御舍设计",
      location: "中国上海",
      construction: "御舍（上海）建设工程有限公司",
      area: "110㎡",
      txtPlace: 1,
      textRlign: "right",
      showType: "single",
      cover: "c1.jpg",
      designConcept: "",
      content: "",
      dtlImgType: "",
      dtlImgs: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
    },
    {
      id: 54,
      ctg: 7,
      ctgName: "户外景观",
      title: "上海大都会",
      design: "杨玥",
      designCom: "御舍设计",
      location: "中国上海",
      construction: "御舍（上海）建设工程有限公司",
      area: "190㎡",
      txtPlace: 7,
      textRlign: "right",
      showType: "type_a", //single type_a type_b
      cover: [
        {
          url: "c1.jpg",
          size: "420x440",
          left: "0",
          top: "0",
        },
        {
          url: "c2.jpg",
          size: "420x440",
          left: "440",
          top: "0",
        },
        {
          url: "c3.jpg",
          size: "420x440",
          left: "880",
          top: "0",
        },
        {
          url: "c4.jpg",
          size: "860x210",
          left: "0",
          top: "460",
        },
        {
          url: "c5.jpg",
          size: "420x210",
          left: "880",
          top: "460",
        },
        {
          url: "c6.jpg",
          size: "420x210",
          left: "0",
          top: "690",
        },
        {
          url: "c7.jpg",
          size: "860x210",
          left: "440",
          top: "690",
        },
      ],
      designConcept: "",
      content: "",
      dtlImgType: "", //full
      dtlImgs: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"],
    },
  ],
};
