module.exports = {
  pro: [{
    "id": 17,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "濮院国贸酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "浙江桐乡",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1300㎡",
    "txtPlace": 4,
    "textRlign": "",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 18,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "山东福乐蒙酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "山东",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "25000㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 19,
    "ctg": 3,
    "delete": true,
    //删除不显示
    "ctgName": "酒店",
    "title": "上海敏帝豪酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "softDesign": "",
    "partDesign": "",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "20000㎡",
    "txtPlace": 1,
    "textRlign": "",
    "showType": "single",
    "cover": "c1.png",
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 20,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海康桥精品酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "20000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 21,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海索菲特大酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "25000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_c",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
  }, {
    "id": 22,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "新安江温泉酒店",
    "design": "李宏升 / 黃東奎",
    "designCom": "御舍设计",
    "location": "浙江杭州",
    "construction": "稼禾（上海）建设工程有限公司",
    "area": "10000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }]
};