module.exports = {
  pro: [{
    "id": 2,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "信华酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "softDesign": "陈婷婷",
    "partDesign": "王景前/刘坤",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "3000㎡",
    "txtPlace": 7,
    "textRlign": "",
    "showType": "single",
    "cover": "c1.jpg",
    "designConcept": "",
    "content": "该项目坐落于有人杰地灵之称的浔阳，酒店以婚礼及宴席为主，寻佳作、觅 佳偶，以此为题展开设计。将浪漫之形高贵之气印染至所目及之处，形神兼 备的传达质感与气氛。",
    "dtlImgType": "full",
    "dtlImgs": ["2.jpg", "3.jpg", "4.jpg", "5.png", "6.jpg", "7.png", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg", "25.jpg", "26.jpg", "27.jpg", "28.jpg", "29.jpg", "30.jpg"]
  }, {
    "id": 15,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "建国龙吟日料餐厅",
    "design": "李宏升",
    "softDesign": "陈婷婷",
    "softDesignSub": "王茜",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "300㎡",
    "txtPlace": 8,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c8.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.png", "6.jpg", "7.png", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg"]
  }, {
    "id": 16,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海隆江大酒店",
    "design": "李宏升",
    "softDesign": "赵晟  陈婷婷",
    "softDesignSub": "王茜",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "600㎡",
    "txtPlace": 7,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["2.png", "3.jpg", "4.jpg", "5.jpg"]
  }, {
    "id": 17,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "濮院国贸酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "浙江桐乡",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1300㎡",
    "txtPlace": 4,
    "textRlign": "",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 18,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "山东福乐蒙酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "山东",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "25000㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 19,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海敏帝豪酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "softDesign": "",
    "partDesign": "",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "20000㎡",
    "txtPlace": 1,
    "textRlign": "",
    "showType": "single",
    "cover": "c1.png",
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 20,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海康桥精品酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "20000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 21,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海索菲特大酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "25000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_c",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
  }, {
    "id": 22,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "新安江温泉酒店",
    "design": "李宏升 / 黃東奎",
    "designCom": "御舍设计",
    "location": "浙江杭州",
    "construction": "稼禾（上海）建设工程有限公司",
    "area": "10000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }]
};