module.exports = {
  pro: [{
    "id": 14,
    "ctg": 2,
    "ctgName": "会所售楼处",
    "title": "芙蕖茶苑会所",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1500㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c6.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"]
  }, {
    "id": 37,
    "ctg": 2,
    "ctgName": "会所售楼处",
    "title": "三银会所",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "area": "",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "13000㎡",
    "txtPlace": 4,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg"]
  }, {
    "id": 38,
    "ctg": 2,
    "ctgName": "会所售楼处",
    "title": "北京当代置业",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国北京",
    "area": "",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "2000㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.jpg", "2.jpg"]
  }, {
    "id": 39,
    "ctg": 2,
    "ctgName": "会所售楼处",
    "title": "常州中海龙城公馆",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江苏常州",
    "area": "",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1800㎡",
    "txtPlace": 1,
    "textRlign": "",
    "showType": "single",
    "cover": "c1.jpg",
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg"]
  }, {
    "id": 40,
    "ctg": 2,
    "ctgName": "会所售楼处",
    "title": "佛山旭辉售楼处",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "广东佛山",
    "area": "",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "2000㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "420x440",
      "left": "0",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c8.jpg",
      "size": "420x210",
      "left": "440",
      "top": "690"
    }, {
      "url": "c9.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
  }]
};