/*
    { "id": 1, "label": "办公空间" },
    { "id": 2, "label": "会所售楼处" },
    { "id": 3, "label": "酒店" },
    { "id": 4, "label": "商业空间" },
    { "id": 5, "label": "私宅样板房别墅" },
    { "id": 6, "label": "文博产业" }
*/
module.exports = {
  proList: [{
    "id": 13,
    "ctg": 1,
    "ctgName": "办公空间",
    "title": "上海谨道电商办公室",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "area": "上海市長寧區長寧來福士辦公樓1A22F",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1000㎡",
    "style": "",
    "txtPlace": 7,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x670",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "以象形文字中品字的形字以馬的蹄印演化而來，而馬的精神正是品優，品質、品格，代表著公司的三位股東精神，及企業形象",
    "content": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.png", "4.jpg", "5.jpg", "6.jpg", "7.png", "8.png"]
  }, {
    "id": 14,
    "ctg": 2,
    "ctgName": "会所售楼处",
    "title": "芙蕖茶苑会所",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1500㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c6.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"]
  }, {
    "id": 2,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "信华酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "softDesign": "陈婷婷",
    "partDesign": "王景前/刘坤",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "3000㎡",
    "txtPlace": 7,
    "textRlign": "",
    "showType": "single",
    "cover": "c1.jpg",
    "designConcept": "",
    "content": "该项目坐落于有人杰地灵之称的浔阳，酒店以婚礼及宴席为主，寻佳作、觅 佳偶，以此为题展开设计。将浪漫之形高贵之气印染至所目及之处，形神兼 备的传达质感与气氛。",
    "dtlImgType": "full",
    "dtlImgs": ["2.jpg", "3.jpg", "4.jpg", "5.png", "6.jpg", "7.png", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg", "25.jpg", "26.jpg", "27.jpg", "28.jpg", "29.jpg", "30.jpg"]
  }, {
    "id": 15,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "建国龙吟日料餐厅",
    "design": "李宏升",
    "softDesign": "陈婷婷",
    "softDesignSub": "王茜",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "300㎡",
    "txtPlace": 8,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c8.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.png", "6.jpg", "7.png", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg"]
  }, {
    "id": 16,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海隆江大酒店",
    "design": "李宏升",
    "softDesign": "赵晟  陈婷婷",
    "softDesignSub": "王茜",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "600㎡",
    "txtPlace": 7,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["2.png", "3.jpg", "4.jpg", "5.jpg"]
  }, {
    "id": 17,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "濮院国贸酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "浙江桐乡",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "1300㎡",
    "txtPlace": 4,
    "textRlign": "",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 18,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "山东福乐蒙酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "山东",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "25000㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "860x210",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 19,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海敏帝豪酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "softDesign": "",
    "partDesign": "",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "20000㎡",
    "txtPlace": 1,
    "textRlign": "",
    "showType": "single",
    "cover": "c1.png",
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 20,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海康桥精品酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "20000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 21,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "上海索菲特大酒店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "25000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_c",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
  }, {
    "id": 22,
    "ctg": 3,
    "ctgName": "酒店",
    "title": "新安江温泉酒店",
    "design": "李宏升 / 黃東奎",
    "designCom": "御舍设计",
    "location": "浙江杭州",
    "construction": "稼禾（上海）建设工程有限公司",
    "area": "10000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "880",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png", "3.png"]
  }, {
    "id": 23,
    "ctg": 4,
    "ctgName": "商业空间",
    "title": "云南贡润祥茶楼",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "云南昆明",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "600㎡",
    "txtPlace": 7,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x440",
      "left": "440",
      "top": "230"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "<div style='width:50%;margin:0 auto; display:flex;justify-content: center;flex-direction:column;align-content: center;align-items: center;'><p><b>溯源，寻味汉韵，茶楼新境</b></p><p>情感如一盏茶汤。</p><p>有茶的恬淡温暖，有俗世的超脱自得。</p><p>得闲相依， 手握杯盏， 聊平淡家常。</p><p>在如此佳境相饮， 相视心明， 日子越发淡定丰盈 </p><br/><br/><p><b>坐标：云南</b></p><p>项目位于云南昆明，一个温度适宜四季如春的旅游胜地。 本案在茶楼中融合多种新鲜元素使主题丰富多元， 体验直观立体， 细节蔓延亮点， 让你舍不得遗漏每一个眼前的精致。</p><br/><br/><p><b>项目：茶楼</b></p><p>茶楼软装项目， 通过传统茶文化融合创意元素， 碰撞摩擦， 酿造出别致韵味的茶楼设计， 同时也展现了设计师对传统茶艺的情怀及个性的灵动， 并从体验度中把控每一个细节。</p><br/> <br/><p>感恩一杯佳茗，</p><p>感恩一段时光，</p><p>感恩一次邂逅，</p><p>感恩一处佳境，</p><p>感恩您的鉴赏。</p>",
    "dtlImgType": "",
    "dtlImgs": ["1.png", "2.png", "2.JPG", "3.png", "3.jpg", "4.png", "5.png", "6.png", "7.png"]
  }, {
    "id": 24,
    "ctg": 4,
    "ctgName": "商业空间",
    "title": "克丽缇娜美容院",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "600㎡",
    "txtPlace": 4,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x440",
      "left": "0",
      "top": "460"
    }, {
      "url": "c4.jpg",
      "size": "420x210",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg"]
  }, {
    "id": 25,
    "ctg": 4,
    "ctgName": "商业空间",
    "title": "邂逅丽江（软装设计）",
    "design": "李宏升 / 张至轩",
    "designCom": "御舍设计",
    "location": "丽江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "700㎡",
    "txtPlace": 4,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "860x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "880",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }],
    "designConcept": "",
    "content": "<div><p>摄影：李迪</p><br/><p>主要材料：柚木、壁布、复古砖、铝板、大理石</p><p style='test-algin:center;line-heihgt:2'><strong>与斑鱼来场抵死缠绵</strong></p><p>以水洗尽，以特殊刀工切薄如纸，将剔透的鱼肉煮熟，涮上酱汁，美味可想而知。</p><p>斑鱼火锅一直以来是以水傍乡的丽江特色之一，而这次要打破传统将原本带有地域性色彩的饮食文化融入时尚之都上海；又以新的面貌呈现在广大的消费者面前，这个是业主方和我们设计团队共同的课题。本土与国际化的揉捏交融，传统与时尚碰撞出了不一样的味道。</p></div>",
    "dtlImgType": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg"]
  }, {
    "id": 26,
    "ctg": 4,
    "ctgName": "商业空间",
    "title": "ZE5酒吧上海店",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "中国上海",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "250㎡",
    "txtPlace": 4,
    "textRlign": "right",
    "showType": "single",
    "cover": "c1.jpg",
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png"]
  }, {
    "id": 27,
    "ctg": 5,
    "ctgName": "私宅样板房别墅",
    "title": "九悦庭雅宅",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "150㎡",
    "txtPlace": 7,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "860x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "<div><p>完成时间：2017年1月</p><p>主要材料：乳胶漆、大理石、藤编壁纸、木饰面</p><p>在家居设计中简约风越来越受到人们的青睐，成为设计界的流行元素，它以少胜多的设计理念，玩转出一个温馨、优雅的家居环境。</p><p>当初这对90后夫妇找到设计师，希望能为他们设计婚房。看着他们一脸欣喜，本着只羡鸳鸯不羡仙的心情，设计师也提出自己的想法同他们一起沟通交流，业主很信任，所以整个工程都很顺利的开展。</p><p>家居设计不仅是停留在家居选择、空间布局、材质、颜色的组合选择等形式上，设计师通过这些外在的设计形式赋予内在的“灵魂内核”，而且也希望业主在今后的生活过程中细细品味日子。</p><p>执着于空间的比例规划设计师巧妙的构思把各个空间流畅的连接起来，让更多的自然光照进室内，而开拓的空间使业主在今后的生活相处中更加轻松愉悦，交流更加便捷。两处空间的艺术挂画和抱枕相映成趣、相互呼应，从而打造强烈的空间感。</p><p>空间整体以高冷灰为主色调来打造极简现代的都市风格，细腻色彩的点缀为空间营造出时尚小资情调。</p></div>",
    "dtlImgType": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg"]
  }, {
    "id": 28,
    "ctg": 5,
    "ctgName": "私宅样板房别墅",
    "title": "庐山私人住宅",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "300㎡",
    "txtPlace": 4,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c4.jpg",
      "size": "860x440",
      "left": "440",
      "top": "460"
    }],
    "designConcept": "在设计中以文化为内核，糅合东西方文化，进行提炼和度越，博百家之长， 将西方住宅文化与本地居住理念融合于装饰设计的设计理念，打上地域与人 文内涵的烙印。",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
  }, {
    "id": 29,
    "ctg": 5,
    "ctgName": "私宅样板房别墅",
    "title": "海南别墅",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "海南",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "2000㎡",
    "txtPlace": 4,
    "textRlign": "right",
    "showType": "type_c",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "460"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
  }, {
    "id": 30,
    "ctg": 5,
    "ctgName": "私宅样板房别墅",
    "title": "江西映日荷花18",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "380㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x440",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x440",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c5.jpg",
      "size": "420x210",
      "left": "880",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c7.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.png", "2.png", "3.png", "4.png", "5.png", "6.png"]
  }, {
    "id": 31,
    "ctg": 5,
    "ctgName": "私宅样板房别墅",
    "title": "江西映日荷花99",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "江西九江",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "2200㎡",
    "txtPlace": 5,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "420x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x440",
      "left": "440",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c4.jpg",
      "size": "420x440",
      "left": "0",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "420x440",
      "left": "440",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "880",
      "top": "230"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c8.jpg",
      "size": "420x210",
      "left": "880",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.png", "2.png", "3.png", "4.png"]
  }, {
    "id": 32,
    "ctg": 5,
    "ctgName": "私宅样板房别墅",
    "title": "浙江余姚私宅",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "浙江余姚",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "150㎡",
    "txtPlace": 1,
    "textRlign": "right",
    "showType": "single",
    "cover": "c1.jpg",
    "designConcept": "",
    "content": "",
    "dtlImgType": "full",
    "dtlImgs": ["1.png", "2.png"]
  }, {
    "id": 33,
    "ctg": 6,
    "ctgName": "文博产业",
    "title": "彼岸塔妙乐寺",
    "design": "李宏升",
    "designCom": "御舍设计",
    "location": "湖北黄冈",
    "construction": "御舍（上海）建设工程有限公司",
    "area": "5000㎡",
    "txtPlace": 6,
    "textRlign": "right",
    "showType": "type_a",
    "cover": [{
      "url": "c1.jpg",
      "size": "860x210",
      "left": "0",
      "top": "0"
    }, {
      "url": "c2.jpg",
      "size": "420x210",
      "left": "880",
      "top": "0"
    }, {
      "url": "c3.jpg",
      "size": "420x210",
      "left": "0",
      "top": "230"
    }, {
      "url": "c4.jpg",
      "size": "860x210",
      "left": "440",
      "top": "230"
    }, {
      "url": "c5.jpg",
      "size": "860x210",
      "left": "0",
      "top": "460"
    }, {
      "url": "c6.jpg",
      "size": "420x210",
      "left": "880",
      "top": "460"
    }, {
      "url": "c7.jpg",
      "size": "420x210",
      "left": "0",
      "top": "690"
    }, {
      "url": "c8.jpg",
      "size": "860x210",
      "left": "440",
      "top": "690"
    }],
    "designConcept": "",
    "content": "",
    "dtlImgType": "",
    "dtlImgs": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg"]
  }]
};